# Generated by Django 5.2 on 2025-05-08 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(default='Various', max_length=100)),
                ('release_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='image/')),
                ('description', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artist')),
            ],
        ),
    ]
