# Generated by Django 5.2 on 2025-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='vinyl',
            name='cover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
