# Generated by Django 5.2 on 2025-05-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vinyl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='image',
            field=models.ImageField(upload_to='vinyl_images/'),
        ),
    ]
