# Generated by Django 5.2 on 2025-05-16 07:02

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='desc_artist',
            field=models.TextField(blank=True, verbose_name=main.models.Artist),
        ),
    ]
