# Generated by Django 5.2 on 2025-05-16 07:13

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vinyl_desc_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='desc_artist',
        ),
        migrations.AddField(
            model_name='vinyl',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='description',
            field=models.TextField(blank=True, verbose_name=main.models.Artist),
        ),
    ]
