# Generated by Django 5.2 on 2025-05-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_vinyl_desc_artist_vinyl_long_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='long_description',
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
