# Generated by Django 5.2 on 2025-05-16 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_vinyl_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinyls', to='main.artist'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vinyl_images/'),
        ),
    ]
