# Generated by Django 5.2 on 2025-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vinyl_artist_alter_vinyl_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='vinyls_hover/'),
        ),
    ]
