# Generated by Django 5.2 on 2025-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
        ('main', '0008_alter_vinyl_artist_alter_vinyl_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='order',
            name='post_type',
            field=models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('meest', 'Meest')], default='nova_poshta', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Обробляється'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='vinyls',
            field=models.ManyToManyField(to='main.vinyl'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
    ]
