# Generated by Django 5.2 on 2025-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_address_remove_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vinyls',
        ),
        migrations.AddField(
            model_name='order',
            name='city_nova_poshta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='order',
            name='city_ukrposhta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukr_poshta', 'Укрпошта')], default='nova_poshta', max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='s', max_length=100, verbose_name="Ім'я клієнта"),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='w', max_length=100, verbose_name='Призвіще клієнта'),
        ),
        migrations.AddField(
            model_name='order',
            name='nova_poshta_branch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер відділення / поштомату'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='03204', max_length=20, verbose_name='Номер телефону клієнта'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Поштовий індекс'),
        ),
        migrations.AddField(
            model_name='order',
            name='products_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Товари (JSON)'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='street_nova_poshta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='order',
            name='street_ukrposhta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='30000', max_digits=10, verbose_name='Загальна сума'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('google_pay', 'Google Pay'), ('apple_pay', 'Apple Pay'), ('cod', 'Післяплата')], max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
