# Generated by Django 5.2 on 2025-05-17 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='city_nova_poshta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто (Нова Пошта)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city_ukrposhta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто (Укрпошта)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я клієнта"),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище клієнта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nova_poshta_branch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Відділення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефону клієнта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_nova_poshta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця (Нова Пошта)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_ukrposhta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця (Укрпошта)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума'),
        ),
    ]
